function [featureTable,outputTable] = GenerateTop20Features(inputData)
%DIAGNOSTICFEATURES recreates results in Diagnostic Feature Designer.
%
% Input:
%  inputData: A table or a cell array of tables/matrices containing the
%  data as those imported into the app.
%
% Output:
%  featureTable: A table containing all features and condition variables.
%  outputTable: A table containing the computation results.
%
% This function computes features:
%  Ax_sigstats/CrestFactor
%  Ax_sigstats/Mean
%  Ax_sigstats/PeakValue
%  Ax_sigstats/RMS
%  Ay_sigstats/ClearanceFactor
%  Ay_sigstats/CrestFactor
%  Ay_sigstats/ImpulseFactor
%  Ay_sigstats/Mean
%  Ay_sigstats/RMS
%  Ay_sigstats/ShapeFactor
%  Gy_sigstats/PeakValue
%  Gy_sigstats/RMS
%  Gy_sigstats/Skewness
%  Gy_sigstats/Std
%  Gz_sigstats/ClearanceFactor
%  Gz_sigstats/CrestFactor
%  Gz_sigstats/ImpulseFactor
%  Gz_sigstats/Kurtosis
%  Gz_sigstats/PeakValue
%  Gz_sigstats/ShapeFactor
%
% Organization of the function:
% 1. Compute signals/spectra/features
% 2. Extract computed features into a table
%
% Modify the function to add or remove data processing, feature generation
% or ranking operations.

% Auto-generated by MATLAB on 11-Sep-2025 15:26:51

% Create output ensemble.
outputEnsemble = workspaceEnsemble(inputData,'DataVariables',["Ax";"Ay";"Az";"Gx";"Gy";"Gz"],'ConditionVariables',"label");

% Reset the ensemble to read from the beginning of the ensemble.
reset(outputEnsemble);

% Append new signal or feature names to DataVariables.
outputEnsemble.DataVariables = unique([outputEnsemble.DataVariables;"Ax_sigstats";"Ay_sigstats";"Gy_sigstats";"Gz_sigstats"],'stable');

% Set SelectedVariables to select variables to read from the ensemble.
outputEnsemble.SelectedVariables = ["Ax","Ay","Gy","Gz"];

% Initialize a cell array to store all the results.
allMembersResult = {};

% Loop through all ensemble members to read and write data.
while hasdata(outputEnsemble)
    % Read one member.
    member = read(outputEnsemble);

    % Get all input variables.
    Ax = readMemberData(member,"Ax","Col1");
    iv = (0:1:(height(Ax)-1)*1)';
    Ax.Sample = iv;
    Ay = readMemberData(member,"Ay","Col1");
    iv = (0:1:(height(Ay)-1)*1)';
    Ay.Sample = iv;
    Gy = readMemberData(member,"Gy","Col1");
    iv = (0:1:(height(Gy)-1)*1)';
    Gy.Sample = iv;
    Gz = readMemberData(member,"Gz","Col1");
    iv = (0:1:(height(Gz)-1)*1)';
    Gz.Sample = iv;

    % Initialize a table to store results.
    memberResult = table;

    %% SignalFeatures
    try
        % Compute signal features.
        inputSignal = Ax.Col1;
        CrestFactor = peak2rms(inputSignal);
        Mean = mean(inputSignal,'omitnan');
        PeakValue = max(abs(inputSignal));
        RMS = rms(inputSignal,'omitnan');

        % Concatenate signal features.
        featureValues = [CrestFactor,Mean,PeakValue,RMS];

        % Store computed features in a table.
        featureNames = {'CrestFactor','Mean','PeakValue','RMS'};
        Ax_sigstats = array2table(featureValues,'VariableNames',featureNames);
    catch
        % Store computed features in a table.
        featureValues = NaN(1,4);
        featureNames = {'CrestFactor','Mean','PeakValue','RMS'};
        Ax_sigstats = array2table(featureValues,'VariableNames',featureNames);
    end

    % Append computed results to the member table.
    memberResult = [memberResult, ...
        table({Ax_sigstats},'VariableNames',{'Ax_sigstats'})]; %#ok<AGROW>

    %% SignalFeatures
    try
        % Compute signal features.
        inputSignal = Ay.Col1;
        ClearanceFactor = max(abs(inputSignal))/(mean(sqrt(abs(inputSignal)))^2);
        CrestFactor = peak2rms(inputSignal);
        ImpulseFactor = max(abs(inputSignal))/mean(abs(inputSignal));
        Mean = mean(inputSignal,'omitnan');
        RMS = rms(inputSignal,'omitnan');
        ShapeFactor = rms(inputSignal,'omitnan')/mean(abs(inputSignal),'omitnan');

        % Concatenate signal features.
        featureValues = [ClearanceFactor,CrestFactor,ImpulseFactor,Mean,RMS,ShapeFactor];

        % Store computed features in a table.
        featureNames = {'ClearanceFactor','CrestFactor','ImpulseFactor','Mean','RMS','ShapeFactor'};
        Ay_sigstats = array2table(featureValues,'VariableNames',featureNames);
    catch
        % Store computed features in a table.
        featureValues = NaN(1,6);
        featureNames = {'ClearanceFactor','CrestFactor','ImpulseFactor','Mean','RMS','ShapeFactor'};
        Ay_sigstats = array2table(featureValues,'VariableNames',featureNames);
    end

    % Append computed results to the member table.
    memberResult = [memberResult, ...
        table({Ay_sigstats},'VariableNames',{'Ay_sigstats'})]; %#ok<AGROW>

    %% SignalFeatures
    try
        % Compute signal features.
        inputSignal = Gy.Col1;
        PeakValue = max(abs(inputSignal));
        RMS = rms(inputSignal,'omitnan');
        Skewness = skewness(inputSignal);
        Std = std(inputSignal,'omitnan');

        % Concatenate signal features.
        featureValues = [PeakValue,RMS,Skewness,Std];

        % Store computed features in a table.
        featureNames = {'PeakValue','RMS','Skewness','Std'};
        Gy_sigstats = array2table(featureValues,'VariableNames',featureNames);
    catch
        % Store computed features in a table.
        featureValues = NaN(1,4);
        featureNames = {'PeakValue','RMS','Skewness','Std'};
        Gy_sigstats = array2table(featureValues,'VariableNames',featureNames);
    end

    % Append computed results to the member table.
    memberResult = [memberResult, ...
        table({Gy_sigstats},'VariableNames',{'Gy_sigstats'})]; %#ok<AGROW>

    %% SignalFeatures
    try
        % Compute signal features.
        inputSignal = Gz.Col1;
        ClearanceFactor = max(abs(inputSignal))/(mean(sqrt(abs(inputSignal)))^2);
        CrestFactor = peak2rms(inputSignal);
        ImpulseFactor = max(abs(inputSignal))/mean(abs(inputSignal));
        Kurtosis = kurtosis(inputSignal);
        PeakValue = max(abs(inputSignal));
        ShapeFactor = rms(inputSignal,'omitnan')/mean(abs(inputSignal),'omitnan');

        % Concatenate signal features.
        featureValues = [ClearanceFactor,CrestFactor,ImpulseFactor,Kurtosis,PeakValue,ShapeFactor];

        % Store computed features in a table.
        featureNames = {'ClearanceFactor','CrestFactor','ImpulseFactor','Kurtosis','PeakValue','ShapeFactor'};
        Gz_sigstats = array2table(featureValues,'VariableNames',featureNames);
    catch
        % Store computed features in a table.
        featureValues = NaN(1,6);
        featureNames = {'ClearanceFactor','CrestFactor','ImpulseFactor','Kurtosis','PeakValue','ShapeFactor'};
        Gz_sigstats = array2table(featureValues,'VariableNames',featureNames);
    end

    % Append computed results to the member table.
    memberResult = [memberResult, ...
        table({Gz_sigstats},'VariableNames',{'Gz_sigstats'})]; %#ok<AGROW>

    % Append all member results to the cell array.
    allMembersResult = [allMembersResult; {memberResult}]; %#ok<AGROW>
end

% Write the results for all members to the ensemble.
writeToMembers(outputEnsemble,allMembersResult)

% Gather all features into a table.
selectedFeatureNames = ["Ax_sigstats/CrestFactor","Ax_sigstats/Mean","Ax_sigstats/PeakValue","Ax_sigstats/RMS","Ay_sigstats/ClearanceFactor","Ay_sigstats/CrestFactor","Ay_sigstats/ImpulseFactor","Ay_sigstats/Mean","Ay_sigstats/RMS","Ay_sigstats/ShapeFactor","Gy_sigstats/PeakValue","Gy_sigstats/RMS","Gy_sigstats/Skewness","Gy_sigstats/Std","Gz_sigstats/ClearanceFactor","Gz_sigstats/CrestFactor","Gz_sigstats/ImpulseFactor","Gz_sigstats/Kurtosis","Gz_sigstats/PeakValue","Gz_sigstats/ShapeFactor"];
featureTable = readFeatureTable(outputEnsemble,'Features',selectedFeatureNames);

% Set SelectedVariables to select variables to read from the ensemble.
outputEnsemble.SelectedVariables = unique([outputEnsemble.DataVariables;outputEnsemble.ConditionVariables;outputEnsemble.IndependentVariables],'stable');

% Gather results into a table.
if nargout > 1
    outputTable = readall(outputEnsemble);
end
end
