function [featureTable,outputTable] = GenerateTop10Features(inputData)
%DIAGNOSTICFEATURES recreates results in Diagnostic Feature Designer.
%
% Input:
%  inputData: A table or a cell array of tables/matrices containing the
%  data as those imported into the app.
%
% Output:
%  featureTable: A table containing all features and condition variables.
%  outputTable: A table containing the computation results.
%
% This function computes features:
%  Ax_sigstats/PeakValue
%  Ay_sigstats/CrestFactor
%  Ay_sigstats/Kurtosis
%  Ay_sigstats/Mean
%  Ay_sigstats/RMS
%  Gx_sigstats/ClearanceFactor
%  Gx_sigstats/ImpulseFactor
%  Gx_sigstats/Kurtosis
%  Gy_sigstats/ShapeFactor
%  Gz_sigstats/Skewness
%
% Organization of the function:
% 1. Compute signals/spectra/features
% 2. Extract computed features into a table
%
% Modify the function to add or remove data processing, feature generation
% or ranking operations.

% Auto-generated by MATLAB on 06-Sep-2025 03:54:59

% Create output ensemble.
outputEnsemble = workspaceEnsemble(inputData,'DataVariables',["Ax";"Ay";"Az";"Gx";"Gy";"Gz"],'ConditionVariables',"label");

% Reset the ensemble to read from the beginning of the ensemble.
reset(outputEnsemble);

% Append new signal or feature names to DataVariables.
outputEnsemble.DataVariables = unique([outputEnsemble.DataVariables;"Ax_sigstats";"Ay_sigstats";"Gx_sigstats";"Gy_sigstats";"Gz_sigstats"],'stable');

% Set SelectedVariables to select variables to read from the ensemble.
outputEnsemble.SelectedVariables = ["Ax","Ay","Gx","Gy","Gz"];

% Initialize a cell array to store all the results.
allMembersResult = {};

% Loop through all ensemble members to read and write data.
while hasdata(outputEnsemble)
    % Read one member.
    member = read(outputEnsemble);

    % Get all input variables.
    Ax = readMemberData(member,"Ax","Col1");
    iv = (0:1:(height(Ax)-1)*1)';
    Ax.Sample = iv;
    Ay = readMemberData(member,"Ay","Col1");
    iv = (0:1:(height(Ay)-1)*1)';
    Ay.Sample = iv;
    Gx = readMemberData(member,"Gx","Col1");
    iv = (0:1:(height(Gx)-1)*1)';
    Gx.Sample = iv;
    Gy = readMemberData(member,"Gy","Col1");
    iv = (0:1:(height(Gy)-1)*1)';
    Gy.Sample = iv;
    Gz = readMemberData(member,"Gz","Col1");
    iv = (0:1:(height(Gz)-1)*1)';
    Gz.Sample = iv;

    % Initialize a table to store results.
    memberResult = table;

    %% SignalFeatures
    try
        % Compute signal features.
        inputSignal = Ax.Col1;
        PeakValue = max(abs(inputSignal));

        % Concatenate signal features.
        featureValues = PeakValue;

        % Store computed features in a table.
        featureNames = {'PeakValue'};
        Ax_sigstats = array2table(featureValues,'VariableNames',featureNames);
    catch
        % Store computed features in a table.
        featureValues = NaN(1,1);
        featureNames = {'PeakValue'};
        Ax_sigstats = array2table(featureValues,'VariableNames',featureNames);
    end

    % Append computed results to the member table.
    memberResult = [memberResult, ...
        table({Ax_sigstats},'VariableNames',{'Ax_sigstats'})]; %#ok<AGROW>

    %% SignalFeatures
    try
        % Compute signal features.
        inputSignal = Ay.Col1;
        CrestFactor = peak2rms(inputSignal);
        Kurtosis = kurtosis(inputSignal);
        Mean = mean(inputSignal,'omitnan');
        RMS = rms(inputSignal,'omitnan');

        % Concatenate signal features.
        featureValues = [CrestFactor,Kurtosis,Mean,RMS];

        % Store computed features in a table.
        featureNames = {'CrestFactor','Kurtosis','Mean','RMS'};
        Ay_sigstats = array2table(featureValues,'VariableNames',featureNames);
    catch
        % Store computed features in a table.
        featureValues = NaN(1,4);
        featureNames = {'CrestFactor','Kurtosis','Mean','RMS'};
        Ay_sigstats = array2table(featureValues,'VariableNames',featureNames);
    end

    % Append computed results to the member table.
    memberResult = [memberResult, ...
        table({Ay_sigstats},'VariableNames',{'Ay_sigstats'})]; %#ok<AGROW>

    %% SignalFeatures
    try
        % Compute signal features.
        inputSignal = Gx.Col1;
        ClearanceFactor = max(abs(inputSignal))/(mean(sqrt(abs(inputSignal)))^2);
        ImpulseFactor = max(abs(inputSignal))/mean(abs(inputSignal));
        Kurtosis = kurtosis(inputSignal);

        % Concatenate signal features.
        featureValues = [ClearanceFactor,ImpulseFactor,Kurtosis];

        % Store computed features in a table.
        featureNames = {'ClearanceFactor','ImpulseFactor','Kurtosis'};
        Gx_sigstats = array2table(featureValues,'VariableNames',featureNames);
    catch
        % Store computed features in a table.
        featureValues = NaN(1,3);
        featureNames = {'ClearanceFactor','ImpulseFactor','Kurtosis'};
        Gx_sigstats = array2table(featureValues,'VariableNames',featureNames);
    end

    % Append computed results to the member table.
    memberResult = [memberResult, ...
        table({Gx_sigstats},'VariableNames',{'Gx_sigstats'})]; %#ok<AGROW>

    %% SignalFeatures
    try
        % Compute signal features.
        inputSignal = Gy.Col1;
        ShapeFactor = rms(inputSignal,'omitnan')/mean(abs(inputSignal),'omitnan');

        % Concatenate signal features.
        featureValues = ShapeFactor;

        % Store computed features in a table.
        featureNames = {'ShapeFactor'};
        Gy_sigstats = array2table(featureValues,'VariableNames',featureNames);
    catch
        % Store computed features in a table.
        featureValues = NaN(1,1);
        featureNames = {'ShapeFactor'};
        Gy_sigstats = array2table(featureValues,'VariableNames',featureNames);
    end

    % Append computed results to the member table.
    memberResult = [memberResult, ...
        table({Gy_sigstats},'VariableNames',{'Gy_sigstats'})]; %#ok<AGROW>

    %% SignalFeatures
    try
        % Compute signal features.
        inputSignal = Gz.Col1;
        Skewness = skewness(inputSignal);

        % Concatenate signal features.
        featureValues = Skewness;

        % Store computed features in a table.
        featureNames = {'Skewness'};
        Gz_sigstats = array2table(featureValues,'VariableNames',featureNames);
    catch
        % Store computed features in a table.
        featureValues = NaN(1,1);
        featureNames = {'Skewness'};
        Gz_sigstats = array2table(featureValues,'VariableNames',featureNames);
    end

    % Append computed results to the member table.
    memberResult = [memberResult, ...
        table({Gz_sigstats},'VariableNames',{'Gz_sigstats'})]; %#ok<AGROW>

    % Append all member results to the cell array.
    allMembersResult = [allMembersResult; {memberResult}]; %#ok<AGROW>
end

% Write the results for all members to the ensemble.
writeToMembers(outputEnsemble,allMembersResult)

% Gather all features into a table.
selectedFeatureNames = ["Ax_sigstats/PeakValue","Ay_sigstats/CrestFactor","Ay_sigstats/Kurtosis","Ay_sigstats/Mean","Ay_sigstats/RMS","Gx_sigstats/ClearanceFactor","Gx_sigstats/ImpulseFactor","Gx_sigstats/Kurtosis","Gy_sigstats/ShapeFactor","Gz_sigstats/Skewness"];
featureTable = readFeatureTable(outputEnsemble,'Features',selectedFeatureNames);

% Set SelectedVariables to select variables to read from the ensemble.
outputEnsemble.SelectedVariables = unique([outputEnsemble.DataVariables;outputEnsemble.ConditionVariables;outputEnsemble.IndependentVariables],'stable');

% Gather results into a table.
if nargout > 1
    outputTable = readall(outputEnsemble);
end
end
